// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Water_Level_Sensor_and_buttons_screen_init(void)
{
ui_Water_Level_Sensor_and_buttons = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Water_Level_Sensor_and_buttons, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_septic_tank = lv_obj_create(ui_Water_Level_Sensor_and_buttons);
lv_obj_remove_style_all(ui_septic_tank);
lv_obj_set_width( ui_septic_tank, 210);
lv_obj_set_height( ui_septic_tank, 241);
lv_obj_set_x( ui_septic_tank, 119 );
lv_obj_set_y( ui_septic_tank, 105 );
lv_obj_set_align( ui_septic_tank, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_septic_tank, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_septic_tank, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_septic_tank, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_septic_tank, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

// Configure septic tank arc here!
ui_Arc3 = lv_arc_create(ui_septic_tank);
lv_obj_set_width( ui_Arc3, 169);
lv_obj_set_height( ui_Arc3, 169);
lv_obj_set_x( ui_Arc3, 6 );
lv_obj_set_y( ui_Arc3, -21 );
lv_obj_set_align( ui_Arc3, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Arc3, 50);
lv_obj_set_style_arc_width(ui_Arc3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x31E6FA), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc3, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_septic_tank);
lv_obj_set_width( ui_Panel2, 132);
lv_obj_set_height( ui_Panel2, 129);
lv_obj_set_x( ui_Panel2, 7 );
lv_obj_set_y( ui_Panel2, -23 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 280, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_septic_tank);
lv_obj_set_width( ui_Panel4, 106);
lv_obj_set_height( ui_Panel4, 104);
lv_obj_set_x( ui_Panel4, 7 );
lv_obj_set_y( ui_Panel4, -22 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel4, 280, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x31E6FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

// SEPTIC TANK LEVEL BELOW !!!
ui_Septic_Level_Value = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Septic_Level_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Septic_Level_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Septic_Level_Value, 2 );
lv_obj_set_y( ui_Septic_Level_Value, 1 );
lv_obj_set_align( ui_Septic_Level_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Septic_Level_Value,"50%");
lv_obj_set_style_text_color(ui_Septic_Level_Value, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Septic_Level_Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Septic_Level_Value, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Septic_Level_Value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Septic_Level_Value, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_water_tank = lv_obj_create(ui_Water_Level_Sensor_and_buttons);
lv_obj_remove_style_all(ui_water_tank);
lv_obj_set_width( ui_water_tank, 210);
lv_obj_set_height( ui_water_tank, 241);
lv_obj_set_x( ui_water_tank, -118 );
lv_obj_set_y( ui_water_tank, 105 );
lv_obj_set_align( ui_water_tank, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_water_tank, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_water_tank, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_water_tank, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_water_tank, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

// CONFIGURE WATER TANK LEVEL ARC BELOW!!!
ui_Arc2 = lv_arc_create(ui_water_tank);
lv_obj_set_width( ui_Arc2, 169);
lv_obj_set_height( ui_Arc2, 169);
lv_obj_set_x( ui_Arc2, 6 );
lv_obj_set_y( ui_Arc2, -21 );
lv_obj_set_align( ui_Arc2, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Arc2, 50); // CHANGE TO ACTUAL SENSOR READING
lv_obj_set_style_arc_width(ui_Arc2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x31E6FA), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc2, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_water_tank);
lv_obj_set_width( ui_Panel3, 132);
lv_obj_set_height( ui_Panel3, 129);
lv_obj_set_x( ui_Panel3, 7 );
lv_obj_set_y( ui_Panel3, -23 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel3, 280, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_water_tank);
lv_obj_set_width( ui_Panel1, 106);
lv_obj_set_height( ui_Panel1, 104);
lv_obj_set_x( ui_Panel1, 7 );
lv_obj_set_y( ui_Panel1, -22 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 280, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x31E6FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

// CONFIGURE WATER LEVEL VALUE BELOW!!!
ui_Water_Level_Value = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Water_Level_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Water_Level_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Water_Level_Value, 2 );
lv_obj_set_y( ui_Water_Level_Value, 1 );
lv_obj_set_align( ui_Water_Level_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Water_Level_Value,"50%");
lv_obj_set_style_text_color(ui_Water_Level_Value, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Water_Level_Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Water_Level_Value, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Water_Level_Value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Water_Level_Value, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Water_Tank_Label = lv_label_create(ui_Water_Level_Sensor_and_buttons);
lv_obj_set_width( ui_Water_Tank_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Water_Tank_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Water_Tank_Label, -114 );
lv_obj_set_y( ui_Water_Tank_Label, 188 );
lv_obj_set_align( ui_Water_Tank_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Water_Tank_Label,"Water Tank");
lv_obj_set_style_text_letter_space(ui_Water_Tank_Label, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Water_Tank_Label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Water_Tank_Label, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Water_Tank_Label, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Water_Tank_Label2 = lv_label_create(ui_Water_Level_Sensor_and_buttons);
lv_obj_set_width( ui_Water_Tank_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Water_Tank_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Water_Tank_Label2, 115 );
lv_obj_set_y( ui_Water_Tank_Label2, 189 );
lv_obj_set_align( ui_Water_Tank_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Water_Tank_Label2,"Septic Tank");
lv_obj_set_style_text_letter_space(ui_Water_Tank_Label2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Water_Tank_Label2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Water_Tank_Label2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Water_Tank_Label2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Light_scene_buttons = lv_obj_create(ui_Water_Level_Sensor_and_buttons);
lv_obj_set_width( ui_Light_scene_buttons, 434);
lv_obj_set_height( ui_Light_scene_buttons, 29);
lv_obj_set_x( ui_Light_scene_buttons, 4 );
lv_obj_set_y( ui_Light_scene_buttons, -206 );
lv_obj_set_align( ui_Light_scene_buttons, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Light_scene_buttons, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_Light_scene_buttons);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 0 );
lv_obj_set_y( ui_Label11, -1 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Light Scene Buttons");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xF3FB54), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_Water_Level_Sensor_and_buttons);
lv_obj_set_width( ui_Panel7, 296);
lv_obj_set_height( ui_Panel7, 26);
lv_obj_set_x( ui_Panel7, 2 );
lv_obj_set_y( ui_Panel7, -43 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Water_Level = lv_label_create(ui_Water_Level_Sensor_and_buttons);
lv_obj_set_width( ui_Water_Level, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Water_Level, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Water_Level, 2 );
lv_obj_set_y( ui_Water_Level, -44 );
lv_obj_set_align( ui_Water_Level, LV_ALIGN_CENTER );
lv_label_set_text(ui_Water_Level,"Water Level");
lv_obj_set_style_text_color(ui_Water_Level, lv_color_hex(0x00EAFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Water_Level, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Water_Level, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Water_Level, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Water_Level, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel9 = lv_obj_create(ui_Water_Level_Sensor_and_buttons);
lv_obj_set_width( ui_Panel9, 196);
lv_obj_set_height( ui_Panel9, 92);
lv_obj_set_x( ui_Panel9, -126 );
lv_obj_set_y( ui_Panel9, -122 );
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Massage_Mode_text = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Massage_Mode_text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Massage_Mode_text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Massage_Mode_text, 0 );
lv_obj_set_y( ui_Massage_Mode_text, -30 );
lv_obj_set_align( ui_Massage_Mode_text, LV_ALIGN_CENTER );
lv_label_set_text(ui_Massage_Mode_text,"Relax");
lv_obj_set_style_text_color(ui_Massage_Mode_text, lv_color_hex(0xF3FB54), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Massage_Mode_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Massage_Mode_text, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Massage_Mode_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Massage_Mode_text, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch4 = lv_switch_create(ui_Panel9);
lv_obj_set_width( ui_Switch4, 100);
lv_obj_set_height( ui_Switch4, 40);
lv_obj_set_x( ui_Switch4, -3 );
lv_obj_set_y( ui_Switch4, 13 );
lv_obj_set_align( ui_Switch4, LV_ALIGN_CENTER );


ui_Panel5 = lv_obj_create(ui_Water_Level_Sensor_and_buttons);
lv_obj_set_width( ui_Panel5, 196);
lv_obj_set_height( ui_Panel5, 92);
lv_obj_set_x( ui_Panel5, 127 );
lv_obj_set_y( ui_Panel5, -121 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Massage_Mode_text1 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Massage_Mode_text1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Massage_Mode_text1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Massage_Mode_text1, -3 );
lv_obj_set_y( ui_Massage_Mode_text1, -29 );
lv_obj_set_align( ui_Massage_Mode_text1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Massage_Mode_text1,"Bright");
lv_obj_set_style_text_color(ui_Massage_Mode_text1, lv_color_hex(0xF3FB54), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Massage_Mode_text1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Massage_Mode_text1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Massage_Mode_text1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Massage_Mode_text1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch1 = lv_switch_create(ui_Panel5);
lv_obj_set_width( ui_Switch1, 100);
lv_obj_set_height( ui_Switch1, 40);
lv_obj_set_x( ui_Switch1, -3 );
lv_obj_set_y( ui_Switch1, 13 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );

}
