// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Water_Level_Sensor_and_buttons
void ui_Water_Level_Sensor_and_buttons_screen_init(void);
lv_obj_t *ui_Water_Level_Sensor_and_buttons;
lv_obj_t *ui_septic_tank;
lv_obj_t *ui_Arc3; // Septic Tank Arc
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Septic_Level_Value;
lv_obj_t *ui_water_tank;
lv_obj_t *ui_Arc2; // Water Tank Arc
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Water_Level_Value;
lv_obj_t *ui_Water_Tank_Label;
lv_obj_t *ui_Water_Tank_Label2;
lv_obj_t *ui_Light_scene_buttons;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_Water_Level;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_Massage_Mode_text;
lv_obj_t *ui_Switch4;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Massage_Mode_text1;
lv_obj_t *ui_Switch1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Water_Level_Sensor_and_buttons_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Water_Level_Sensor_and_buttons);
}
