// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

// #include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Water_Level_Sensor_and_buttons
void ui_Water_Level_Sensor_and_buttons_screen_init(void);
extern lv_obj_t *ui_Water_Level_Sensor_and_buttons;
extern lv_obj_t *ui_septic_tank;
extern lv_obj_t *ui_Arc3;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Septic_Level_Value;
extern lv_obj_t *ui_water_tank;
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Water_Level_Value;
extern lv_obj_t *ui_Water_Tank_Label;
extern lv_obj_t *ui_Water_Tank_Label2;
extern lv_obj_t *ui_Light_scene_buttons;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Water_Level;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Massage_Mode_text;
extern lv_obj_t *ui_Switch4;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Massage_Mode_text1;
extern lv_obj_t *ui_Switch1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
